//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetaboCoins.Resx {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetaboCoins.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Osiągnij obrót celem odblokowania metaboCoins.
        /// </summary>
        public static string StringAchieveTurnover {
            get {
                return ResourceManager.GetString("StringAchieveTurnover", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rozliczone.
        /// </summary>
        public static string StringCleared {
            get {
                return ResourceManager.GetString("StringCleared", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zamknij.
        /// </summary>
        public static string StringClose {
            get {
                return ResourceManager.GetString("StringClose", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa firmy.
        /// </summary>
        public static string StringCompanyName {
            get {
                return ResourceManager.GetString("StringCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd połączenia.
        /// </summary>
        public static string StringConnectionError {
            get {
                return ResourceManager.GetString("StringConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kontakt.
        /// </summary>
        public static string StringContact {
            get {
                return ResourceManager.GetString("StringContact", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Skontaktuj się z podaną osobą ze wsparcia.
        /// </summary>
        public static string StringContactTheSupport {
            get {
                return ResourceManager.GetString("StringContactTheSupport", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Skontaktuj się z nami!.
        /// </summary>
        public static string StringContactUs {
            get {
                return ResourceManager.GetString("StringContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Skontaktuj się z nami. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fringilla adipiscing eu, feugiat tellus dis. Lacus semper turpis lectus elementum. Non id convallis arcu sit nunc imperdiet vel tellus. Viverra elementum lobortis mi aliquam nunc ipsum volutpat natoque..
        /// </summary>
        public static string StringContactUsMessage {
            get {
                return ResourceManager.GetString("StringContactUsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie pamiętasz hasła?.
        /// </summary>
        public static string StringDontYouRememberThePassword {
            get {
                return ResourceManager.GetString("StringDontYouRememberThePassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Potrzebujesz wsparcia?.
        /// </summary>
        public static string StringDoYouNeedSupport {
            get {
                return ResourceManager.GetString("StringDoYouNeedSupport", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Duplikat.
        /// </summary>
        public static string StringDuplicate {
            get {
                return ResourceManager.GetString("StringDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Email.
        /// </summary>
        public static string StringEmail {
            get {
                return ResourceManager.GetString("StringEmail", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adres email.
        /// </summary>
        public static string StringEmailAdress {
            get {
                return ResourceManager.GetString("StringEmailAdress", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd.
        /// </summary>
        public static string StringError {
            get {
                return ResourceManager.GetString("StringError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd podczas skanowania produktu.
        ///Spróbuj ponownie później..
        /// </summary>
        public static string StringErrorWhileScanning {
            get {
                return ResourceManager.GetString("StringErrorWhileScanning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do rozliczenia.
        /// </summary>
        public static string StringForSettlement {
            get {
                return ResourceManager.GetString("StringForSettlement", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Historia.
        /// </summary>
        public static string StringHistory {
            get {
                return ResourceManager.GetString("StringHistory", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd po stronie serwera.
        /// </summary>
        public static string StringInternalError {
            get {
                return ResourceManager.GetString("StringInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Login.
        /// </summary>
        public static string StringLogin {
            get {
                return ResourceManager.GetString("StringLogin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd logowania.
        /// </summary>
        public static string StringLoginError {
            get {
                return ResourceManager.GetString("StringLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Spróbuj ponownie upewniając się że podałeś prawidłowe dane logowania i hasło. W razie konieczności skontaktuj się z nami telefonicznie lub mailowo..
        /// </summary>
        public static string StringLoginErrorMessage {
            get {
                return ResourceManager.GetString("StringLoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu metaboCoins do wykorzystania.
        /// </summary>
        public static string StringMetaboCoinsToUse {
            get {
                return ResourceManager.GetString("StringMetaboCoinsToUse", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak połączenia z serwerem.
        /// </summary>
        public static string StringNoConnectionToTheServer {
            get {
                return ResourceManager.GetString("StringNoConnectionToTheServer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak danych.
        /// </summary>
        public static string StringNoData {
            get {
                return ResourceManager.GetString("StringNoData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hasło.
        /// </summary>
        public static string StringPassword {
            get {
                return ResourceManager.GetString("StringPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Numer telefonu.
        /// </summary>
        public static string StringPhoneNumber {
            get {
                return ResourceManager.GetString("StringPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Liczba punktów.
        /// </summary>
        public static string StringPointsAmount {
            get {
                return ResourceManager.GetString("StringPointsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Profil.
        /// </summary>
        public static string StringProfile {
            get {
                return ResourceManager.GetString("StringProfile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Przypomnij hasło..
        /// </summary>
        public static string StringRemindPassword {
            get {
                return ResourceManager.GetString("StringRemindPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Skanuj.
        /// </summary>
        public static string StringScan {
            get {
                return ResourceManager.GetString("StringScan", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd skanowania - duplikat.
        /// </summary>
        public static string StringScanFailureDuplicate {
            get {
                return ResourceManager.GetString("StringScanFailureDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zeskanuj produkt.
        /// </summary>
        public static string StringScanTheProduct {
            get {
                return ResourceManager.GetString("StringScanTheProduct", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zaloguj się.
        /// </summary>
        public static string StringSignIn {
            get {
                return ResourceManager.GetString("StringSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu S/N produktu.
        /// </summary>
        public static string StringSNProduct {
            get {
                return ResourceManager.GetString("StringSNProduct", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Stan.
        /// </summary>
        public static string StringState {
            get {
                return ResourceManager.GetString("StringState", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sukces.
        /// </summary>
        public static string StringSuccess {
            get {
                return ResourceManager.GetString("StringSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Produkt został dodany!.
        /// </summary>
        public static string StringTheProductHasBeenAdded {
            get {
                return ResourceManager.GetString("StringTheProductHasBeenAdded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dane tego urządzenia istnieją już w naszym systemie i nie mogą być ponownie doliczone do Twojego konta..
        /// </summary>
        public static string StringThisDeviceAlreadyExists {
            get {
                return ResourceManager.GetString("StringThisDeviceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Obrót w AKU.
        /// </summary>
        public static string StringTurnoveInAKU {
            get {
                return ResourceManager.GetString("StringTurnoveInAKU", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Próg obrotu do osiągnięcia.
        /// </summary>
        public static string StringTurnoverThresholdToBeReached {
            get {
                return ResourceManager.GetString("StringTurnoverThresholdToBeReached", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Twoje metaboCoins.
        /// </summary>
        public static string StringYourMetaboCoins {
            get {
                return ResourceManager.GetString("StringYourMetaboCoins", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Twój obrót.
        /// </summary>
        public static string StringYourTurnover {
            get {
                return ResourceManager.GetString("StringYourTurnover", resourceCulture);
            }
        }
    }
}
